import * as dotenv from 'dotenv';

dotenv.config();

const APP_PORT = +process.env.APP_PORT || 4001;
const SPLURGE_SWANLING_MICROSERVICE_URL =
  process.env.SPLURGE_SWANLING_MICROSERVICE_URL || 'http://127.0.0.1:4000/swanling';
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID || '-';
const FIREBASE_ISSUER = process.env.FIREBASE_ISSUER || '-';
const FIREBASE_CREDENTIALS = process.env.FIREBASE_CREDENTIALS || '-';

export { APP_PORT, SPLURGE_SWANLING_MICROSERVICE_URL, FIREBASE_CREDENTIALS, FIREBASE_ISSUER, FIREBASE_PROJECT_ID };
